repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        exclude: /migrations
        args: ['--profile', 'black']

      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        exclude: /migrations
        args: ["--line-length=120"]

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        exclude: /migrations
        args: [
          '--max-line-length=120',
          '--extend-ignore=D104,D100,B008,W503,VNE001',
        ]

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        exclude: /migrations
        args: ["--ignore-missing-imports"]
