services:
  main-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main-app
    ports:
      - "${DJANGO_PORT}:8000"
    command: "sh ./entrypoint.sh"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app/

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery-worker
    command: "celery -A your_project_name worker -l INFO"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app/

  postgres:
    image: postgres:latest
    container_name: db
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: redis
    volumes:
      - redis_data:/data
    expose:
      - "6379"

volumes:
  postgres_data:
  redis_data:
